[build]
  publish = "dist"
  command = "npm run build"
  
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
  
# Environment variables - these need to be set in Netlify dashboard
# VITE_CLERK_PUBLISHABLE_KEY = "your_clerk_key_here"
# VITE_SUPABASE_URL = "your_supabase_url_here"
# VITE_SUPABASE_ANON_KEY = "your_supabase_anon_key_here"
# VITE_GEMINI_API_KEY = "your_gemini_api_key_here"
# VITE_GEMINI_API_KEY_2 = "your_second_gemini_api_key_here"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"